GRANT CONNECT, CREATE ON DATABASE analytics TO etl_user;

CREATE SCHEMA IF NOT EXISTS homework AUTHORIZATION etl_user;

GRANT USAGE, CREATE ON SCHEMA homework TO etl_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA homework TO etl_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA homework TO etl_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA homework
  GRANT ALL PRIVILEGES ON TABLES TO etl_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA homework
  GRANT ALL PRIVILEGES ON SEQUENCES TO etl_user;

CREATE SCHEMA IF NOT EXISTS ml_results AUTHORIZATION etl_user;

GRANT USAGE, CREATE ON SCHEMA ml_results TO etl_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ml_results TO etl_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ml_results TO etl_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA ml_results
  GRANT ALL PRIVILEGES ON TABLES TO etl_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA ml_results
  GRANT ALL PRIVILEGES ON SEQUENCES TO etl_user;